wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
batch_size:
  desc: null
  value: 128
bk:
  desc: null
  value: true
dr:
  desc: null
  value: 1.0
edim:
  desc: null
  value: 200
hidden_dropout1:
  desc: null
  value: 0.2
hidden_dropout2:
  desc: null
  value: 0.3
input_dropout:
  desc: null
  value: 0.2
label_smoothing:
  desc: null
  value: 0.2
lr:
  desc: null
  value: 0.005
num_iterations:
  desc: null
  value: 20
rdim:
  desc: null
  value: 7
