wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
batch_size:
  desc: null
  value: 128
dr:
  desc: null
  value: 1
edim:
  desc: null
  value: 200
hidden_dropout1:
  desc: null
  value: 0.49614455695054993
hidden_dropout2:
  desc: null
  value: 0.3840193074368752
input_dropout:
  desc: null
  value: 0.2304898116576226
label_smoothing:
  desc: null
  value: 0.1
lr:
  desc: null
  value: 0.0010906718438099933
num_iterations:
  desc: null
  value: 82
rdim:
  desc: null
  value: 22
