wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
batch_size:
  desc: null
  value: 128
bk:
  desc: null
  value:
    Background Knowledge: 'Off'
dr:
  desc: null
  value: 0.99
edim:
  desc: null
  value: 200
hidden_dropout1:
  desc: null
  value: 0.47183953238087384
hidden_dropout2:
  desc: null
  value: 0.3606086949178883
input_dropout:
  desc: null
  value: 0.4561321675759945
label_smoothing:
  desc: null
  value: 0.1
lr:
  desc: null
  value: 0.014910421830035067
num_iterations:
  desc: null
  value: 28
rdim:
  desc: null
  value: 15
