wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
batch_size:
  desc: null
  value: 128
dr:
  desc: null
  value: 1
edim:
  desc: null
  value: 200
hidden_dropout1:
  desc: null
  value: 0.15201523140651763
hidden_dropout2:
  desc: null
  value: 0.22408587092645185
input_dropout:
  desc: null
  value: 0.18683087106486715
label_smoothing:
  desc: null
  value: 0.1
lr:
  desc: null
  value: 0.037881195061121156
num_iterations:
  desc: null
  value: 42
rdim:
  desc: null
  value: 6
