wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
batch_size:
  desc: null
  value: 128
dr:
  desc: null
  value: 0.995
edim:
  desc: null
  value: 200
hidden_dropout1:
  desc: null
  value: 0.16053222231248465
hidden_dropout2:
  desc: null
  value: 0.42971139774511613
input_dropout:
  desc: null
  value: 0.41584178767188307
label_smoothing:
  desc: null
  value: '0.'
lr:
  desc: null
  value: 0.048924354021126604
num_iterations:
  desc: null
  value: 64
rdim:
  desc: null
  value: 8
